--Desafio: relatório de vendas

CREATE PROCEDURE FaturamentoSaborPorDepartamento (@dataInicial DATE, @dataFinal DATE)
AS
BEGIN
DECLARE @DEPARTAMENTO TABLE (SABOR VARCHAR(20), DEPARTAMENTO VARCHAR(20))

INSERT INTO @DEPARTAMENTO 
SELECT DISTINCT SABOR, 'FRUTAS NÃO CÍTRICAS' as DEPARTAMENTO 
FROM [TABELA DE PRODUTOS] WHERE 
SABOR IN ('Açai','Cereja','Cereja/Maça','Maça','Manga','Maracujá','Melância')
UNION
SELECT DISTINCT SABOR, 'FRUTAS CÍTRICAS' as DEPARTAMENTO 
FROM [TABELA DE PRODUTOS] WHERE 
SABOR IN ('Laranja','Uva','Limão','Morango','Morango/Limão','Lima/Limão')
SELECT DP.[DEPARTAMENTO]
, SUM(INF.QUANTIDADE * INF.[PREÇO]) AS FATURAMENTO
FROM [TABELA DE PRODUTOS] TP
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
INNER JOIN @DEPARTAMENTO DP
ON TP.SABOR = DP.SABOR
WHERE NF.DATA >= @dataInicial AND NF.DATA <= @dataFinal
GROUP BY DP.[DEPARTAMENTO]
END;

exec FaturamentoSaborPorDepartamento '2017-01-01','2017-01-25';