--Desafio: lista de nomes de funcionários

CREATE TABLE FUNCIONARIOS
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
SALARIO FLOAT NOT NULL
);

INSERT INTO FUNCIONARIOS
VALUES
('Fulano', 1500.00),
('Sicrano', 2000.50),
('Beltrano', 3350.00);

DECLARE @NOME VARCHAR(50);

DECLARE FUNCIONARIO_CURSOR CURSOR FOR
    SELECT NOME
    FROM FUNCIONARIOS;

OPEN FUNCIONARIO_CURSOR

FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @NOME;

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'Nome: ' + @NOME;
    FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @NOME;
END

CLOSE FUNCIONARIO_CURSOR
DEALLOCATE FUNCIONARIO_CURSOR


--Desafio: vendas por mês

CREATE TABLE VENDAS
(
ID INT IDENTITY(1,1) PRIMARY KEY,
DATA_VENDA DATE NOT NULL,
VALOR_VENDA MONEY NOT NULL
);

INSERT INTO VENDAS
VALUES
('2015-04-01', 1500.00),
('2010-07-01', 2000.50),
('2021-11-01', 1150.00),
('2011-09-01', 4990.40),
('2022-06-01', 3350.10),
('2018-01-01', 1320.20),
('2012-03-01', 3670.00),
('2005-05-01', 2630.00);

DECLARE @DATA_VENDA DATE, @VALOR_VENDA MONEY;

DECLARE @janeiro MONEY, @fevereiro MONEY, @marco MONEY, @abril MONEY, @maio MONEY, @junho MONEY,
@julho MONEY, @agosto MONEY, @setembro MONEY, @outubro MONEY, @novembro MONEY, @dezembro MONEY;

SET @janeiro = 0;
SET @fevereiro = 0;
SET @marco = 0;
SET @abril = 0;
SET @maio = 0;
SET @junho = 0;
SET @julho = 0;
SET @agosto = 0;
SET @setembro = 0;
SET @outubro = 0;
SET @novembro = 0;
SET @dezembro = 0;

DECLARE VENDAS_CURSOR CURSOR FOR
    SELECT DATA_VENDA, VALOR_VENDA
    FROM VENDAS

OPEN VENDAS_CURSOR

FETCH NEXT FROM VENDAS_CURSOR INTO @DATA_VENDA, @VALOR_VENDA

WHILE @@FETCH_STATUS = 0
BEGIN
    IF MONTH(@DATA_VENDA) = 1
        SET @janeiro = @janeiro + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 2
        SET @fevereiro = @fevereiro + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 3
        SET @marco = @marco + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 4
        SET @abril = @abril + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 5
        SET @maio = @maio + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 6
        SET @junho = @junho + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 7
        SET @julho = @julho + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 8
        SET @agosto = @agosto + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 9
        SET @setembro = @setembro + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 10
        SET @outubro = @outubro + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 11
        SET @novembro = @novembro + @VALOR_VENDA
    IF MONTH(@DATA_VENDA) = 12
        SET @dezembro = @dezembro + @VALOR_VENDA

    FETCH NEXT FROM VENDAS_CURSOR INTO @DATA_VENDA, @VALOR_VENDA
END

CLOSE VENDAS_CURSOR
DEALLOCATE VENDAS_CURSOR

PRINT 'Janeiro: R$' + CAST(@janeiro AS VARCHAR(20));
PRINT 'Fevereiro: R$' + CAST(@fevereiro AS VARCHAR(20));
PRINT 'Março: R$' + CAST(@marco AS VARCHAR(20));
PRINT 'Abril: R$' + CAST(@abril AS VARCHAR(20));
PRINT 'Maio: R$' + CAST(@maio AS VARCHAR(20));
PRINT 'Junho: R$' + CAST(@junho AS VARCHAR(20));
PRINT 'Julho: R$' + CAST(@julho AS VARCHAR(20));
PRINT 'Agosto: R$' + CAST(@agosto AS VARCHAR(20));
PRINT 'Setembro: R$' + CAST(@setembro AS VARCHAR(20));
PRINT 'Outubro: R$' + CAST(@outubro AS VARCHAR(20));
PRINT 'Novembro: R$' + CAST(@novembro AS VARCHAR(20));
PRINT 'Dezembro: R$' + CAST(@dezembro AS VARCHAR(20));


--Desafio: seleção de vendedor

DECLARE @VENDEDOR_ALEATORIO VARCHAR(12)
DECLARE @VAL_INICIAL INT
DECLARE @VAL_FINAL INT
DECLARE @ALEATORIO INT
DECLARE @CONTADOR INT
SET @CONTADOR = 1 
SET @VAL_INICIAL = 1
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE VENDEDORES]
SET @ALEATORIO = dbo.[NumeroAleatorio](@VAL_INICIAL,@VAL_FINAL)

DECLARE CURSOR1 CURSOR FOR SELECT MATRICULA FROM [TABELA DE VENDEDORES]

OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @VENDEDOR_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
    FETCH NEXT FROM CURSOR1 INTO @VENDEDOR_ALEATORIO
    SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSOR1
DEALLOCATE CURSOR1

SELECT @VENDEDOR_ALEATORIO, @ALEATORIO;
SELECT * FROM [TABELA DE VENDEDORES];